#!/bin/bach
sudo -u $CURRENT_USER code --install-extension 2gua.rainbow-brackets
sudo -u $CURRENT_USER code --install-extension abusaidm.html-snippets
sudo -u $CURRENT_USER code --install-extension alex-pex.theme-darkula
sudo -u $CURRENT_USER code --install-extension angular.ng-template
sudo -u $CURRENT_USER code --install-extension ashksh.darker-one
sudo -u $CURRENT_USER code --install-extension austin.code-gnu-global
sudo -u $CURRENT_USER code --install-extension christian-kohler.path-intellisense
sudo -u $CURRENT_USER code --install-extension dbaeumer.vscode-eslint
sudo -u $CURRENT_USER code --install-extension donjayamanne.githistory
sudo -u $CURRENT_USER code --install-extension donjayamanne.python-extension-pack
sudo -u $CURRENT_USER code --install-extension eamodio.gitlens
sudo -u $CURRENT_USER code --install-extension ecmel.vscode-html-css
sudo -u $CURRENT_USER code --install-extension equinusocio.vsc-community-material-theme
sudo -u $CURRENT_USER code --install-extension equinusocio.vsc-material-theme
sudo -u $CURRENT_USER code --install-extension equinusocio.vsc-material-theme-icons
sudo -u $CURRENT_USER code --install-extension esbenp.prettier-vscode
sudo -u $CURRENT_USER code --install-extension formulahendry.code-runner
sudo -u $CURRENT_USER code --install-extension ghgofort.neon-vommit
sudo -u $CURRENT_USER code --install-extension gruntfuggly.todo-tree
sudo -u $CURRENT_USER code --install-extension johnpapa.angular2
sudo -u $CURRENT_USER code --install-extension kevinrose.vsc-python-indent
sudo -u $CURRENT_USER code --install-extension kiteco.kite
sudo -u $CURRENT_USER code --install-extension kiteco.kite
sudo -u $CURRENT_USER code --install-extension magicstack.magicpython
sudo -u $CURRENT_USER code --install-extension ms-azuretools.vscode-docker
sudo -u $CURRENT_USER code --install-extension ms-mssql.mssql
sudo -u $CURRENT_USER code --install-extension ms-python.python
sudo -u $CURRENT_USER code --install-extension ms-vscode.cpptools
sudo -u $CURRENT_USER code --install-extension ms-vsliveshare.vsliveshare
sudo -u $CURRENT_USER code --install-extension naumovs.color-highlight
sudo -u $CURRENT_USER code --install-extension oderwat.indent-rainbow
sudo -u $CURRENT_USER code --install-extension pkief.material-icon-theme
sudo -u $CURRENT_USER code --install-extension redhat.java
sudo -u $CURRENT_USER code --install-extension ritwickdey.liveserver
sudo -u $CURRENT_USER code --install-extension streetsidesoftware.code-spell-checker
sudo -u $CURRENT_USER code --install-extension syler.sass-indented
sudo -u $CURRENT_USER code --install-extension telerik.nativescript
sudo -u $CURRENT_USER code --install-extension that70schris.arcade
sudo -u $CURRENT_USER code --install-extension tht13.python
sudo -u $CURRENT_USER code --install-extension visualstudioexptteam.vscodeintellicode
sudo -u $CURRENT_USER code --install-extension vscjava.vscode-java-debug
sudo -u $CURRENT_USER code --install-extension vscjava.vscode-java-dependency
sudo -u $CURRENT_USER code --install-extension vscjava.vscode-java-pack
sudo -u $CURRENT_USER code --install-extension vscjava.vscode-java-test
sudo -u $CURRENT_USER code --install-extension vscjava.vscode-maven
sudo -u $CURRENT_USER code --install-extension vscode-icons-team.vscode-icons
sudo -u $CURRENT_USER code --install-extension wayou.vscode-todo-highlight
sudo -u $CURRENT_USER code --install-extension wholroyd.jinja
sudo -u $CURRENT_USER code --install-extension wwwalkerrun.nativescript-ng2-snippets
sudo -u $CURRENT_USER code --install-extension zignd.html-css-class-completion